local Colors = require('rearkitekt.core.colors')
local hexrgb = Colors.hexrgb

local M = {}

M.TILE = {
  MIN_WIDTH = 80,
  MAX_WIDTH = 300,
  DEFAULT_WIDTH = 120,
  WIDTH_STEP = 30,
  
  MIN_HEIGHT = 60,
  MAX_HEIGHT = 400,
  DEFAULT_HEIGHT = 140,
  HEIGHT_STEP = 30,
  
  GAP = 4,
  TEXT_PADDING = 2,
  ROUNDING = 2,
}

M.LAYOUT = {
  MIDI_SECTION_RATIO = 0.35,
  AUDIO_SECTION_RATIO = 0.65,
  
  CONTENT_START_Y = 0.15,
  CONTENT_HEIGHT = 0.8,
  
  SECTION_SPACING = 60,
  HEADER_HEIGHT = 30,
  PADDING = 10,
  
  SEARCH_WIDTH_RATIO = 0.2,
}

M.CACHE = {
  MAX_ENTRIES = 200,
}

M.COLORS = {
  HOVER_OVERLAY = hexrgb("#FFFFFF20"),
  TEXT_SHADOW = hexrgb("#00000050"),
  DEFAULT_TRACK_COLOR = {85/256, 91/256, 91/256},
}

M.GRID = {
  ANIMATION_ENABLED = true,
  SPAWN_DURATION = 0.28,
  DESTROY_DURATION = 0.10,
}

function M.validate()
  assert(M.TILE.MIN_WIDTH <= M.TILE.DEFAULT_WIDTH, "MIN_WIDTH must be <= DEFAULT_WIDTH")
  assert(M.TILE.DEFAULT_WIDTH <= M.TILE.MAX_WIDTH, "DEFAULT_WIDTH must be <= MAX_WIDTH")
  assert(M.TILE.MIN_HEIGHT <= M.TILE.DEFAULT_HEIGHT, "MIN_HEIGHT must be <= DEFAULT_HEIGHT")
  assert(M.TILE.DEFAULT_HEIGHT <= M.TILE.MAX_HEIGHT, "DEFAULT_HEIGHT must be <= MAX_HEIGHT")
  assert(M.LAYOUT.MIDI_SECTION_RATIO + M.LAYOUT.AUDIO_SECTION_RATIO <= 1.0, "Section ratios must sum to <= 1.0")
end

M.validate()

return M